### ISSUE TITLE
How is the code licensed?

### ISSUE THREAD

**Issue by ChristianKitte** [kurapan/CRNN#2]
Hello Kurapan,
thanks for the implementation inKeras, which was very instructive for me. Unfortunately, I can't find any information about the license and its possible uses. Can you tell me under which license the code is published here? Many thanks in advance.

**Comment by kurapan** [comment]
Hello Christian!
Sorry for the inconvenience. I've added a license file to the project. It's MIT.

**Comment by ChristianKitte** [comment]
Thanks a lot! Now I can use the code. This helps a lot :)
